### ISSUE TITLE
numvcpus is ignored when used with clone_from_vm

### ISSUE THREAD

**Issue by vioan** [josenk/terraform-provider-esxi#100]
Hi,

I used packer to create a VM which I use as a template for new VMs provisioned with this plugin. But even if I have added numvcpus = "2" in the "resource" it seems that the created VM is still using one CPU (which is used as default but also the template VM was using one CPU when created with packer). Any idea why? Did I miss something?

I tried also to change the memory of the new VM using "memsize" and it is working.

Thanks a lot!

**Comment by josenk** [comment]
Certain guestos options are limited to 1 cpu, especially some very old os's or 'other'.   You may want to verify you are using a valid  guestos and virthwver.

**Comment by vioan** [comment]
Here is what I use:
```
resource "esxi_guest" "demo" {
  guest_name = "DemoVM"
  disk_store = "LocalSSD"
  guestos    = "centos7-64" # optional, will be taken from source VM anyway

  boot_disk_type = "thin"

  memsize  = "2048"
  numvcpus = "2"
  # resource_pool_name = "/" # not really needed anyway the default is "/"
  power = "on"

  #  clone_from_vm uses ovftool to clone an existing Guest on your esxi host
  clone_from_vm = "centos7-base-packer"

  # add a network interface
  network_interfaces {
    virtual_network = "VM Network"
    nic_type        = "e1000" # this value is default as well
  }

  guest_startup_timeout  = 45
  guest_shutdown_timeout = 30
```
and the packer VM was created with:

```
        "vcpu_number": "1",
        "memory_size": "2048",
        "disk_size": "20000"
```

**Comment by josenk** [comment]
I use clone_from_vm all the time and the number of cpus works correctly.    I don't use/have packer, so I don't know what it's really doing???   I wasn't able to re-create your problem.

1) If you run `terraform plan/apply` again a second time, does it "fix" or attempt to fix the number of vcpus?

2) You can try enabling terraform debugging to see if there's anything in the debug logs.  Run the following before terraform apply
```
export TF_LOG=DEBUG
```

3) Try a different source VM.   Does it work?  Are you only having problems with packer sources?

**Comment by pc-star** [comment]
I am currently testing a similar configuration to yours, using packer to generate the VM, and then spin it up via terraform. Still I can see that the configuration it changes based on what it is write inside the main.tf file

```
main.tf

resource "esxi_guest" "centos" {
  guest_name         = "centos"
  disk_store         = "data"

  memsize            = "4096"
  numvcpus           = "1" 

  #
  #  specify an existing guest to clone, an ovf source, or neither to build a bare-metal guest vm.
  #
  #resource_pool_name = "/"
  clone_from_vm      = "centos-7"
  #ovf_source        = "/local_path/centos-7.vmx"

  network_interfaces {
    virtual_network = "VM Network"
  }
}

#
# substitute ip_address with * in order to get all the available values.
#

output "ip_address" {
  value = "${esxi_guest.centos.ip_address}"
}
```

and the relevant part inside the packer json

```
[...]
       "guest_os_type": "centos7-64",
       "keep_registered": "true",
       "vm_name": "centos-7",
       "vnc_disable_password": "true",
       "cpus": 2,
       "cores": 2,
       "memory": "2048",
       "disk_adapter_type": "scsi",
       "disk_size": "10000",
       "disk_type_id": "zeroedthick",
       "vmx_data": {
        "ethernet0.networkName": "VM Network",
        "ethernet0.adapterType": "e1000"
       },
[...]
```

what I would like to suggest as a further check, apart from what already suggested, it is to comment the `guestos` as something it will recognize once the VM will spin up, anyway.

**Comment by josenk** [comment]
@pc-star   So basically, are you reporting that the plugin is working as expected?

**Comment by pc-star** [comment]
@josenk : yes, that was the intent of my comment. I tried it more than once, but only using CentOS images build via packer. I was not able to reproduce the error @vioan was reporting.

I can successfully change the nmvcpus and memsize values via terraform plugin, and see those changes reflected in the ESXi machine, time it is build up. If required I can send screenshots, and where necessary logs ( if any ), to proof it.

**Comment by josenk** [comment]
Thanks for confirming. No screenshot is required...  
   I don't need proof that it works.    I just need proof that it doesn't work.

**Comment by DimDroll** [comment]
I have proof it doesn't work.

My tf is:
`resource "esxi_guest" "light" {
  guest_name         = "light.local"
  disk_store         = var.disk_store

  numvcpus           = "2"
  memsize            = "4096"
  boot_disk_size     = "50" # in Gb
  boot_disk_type     = "zeroedthick"
  power              = "off"

  clone_from_vm      = "template-centos-7"

  guestinfo = {
    "userdata.encoding" = "gzip+base64"
    "userdata"          = base64gzip(data.template_file.light.rendered)
  }

  network_interfaces {
    virtual_network = "VM Network"
    }

}

data "template_file" "light" {
  template = file("userdata.tpl")
  vars = {
    HOSTNAME = "light.local"
  }
}`

I noticed in vsphere client a failed event:

> Export Vm
> Key: haTask-14-vim.VirtualMachine.exportVm-199500
> Description: Exports the virtual machine as an OVF template
> Virtual machine: template-centos-7
> State: Failed - The task was canceled by a user.

Finally, when I enabled debug during terraform apply, I found this:
`2020/04/09 12:01:25 [WARN] Provider "registry.terraform.io/-/esxi" produced an unexpected new value for esxi_guest.light, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .numvcpus: was cty.StringVal("2"), but now cty.StringVal("")`

Also, above this message, I found following two places where cpu is mentioned:
`2020/04/09 11:58:18 [TRACE] Completed graph transform *terraform.TargetsTransformer (no changes)
2020/04/09 11:58:18 [TRACE] Executing graph transform *terraform.CloseProviderTransformer
      ^[[32m+^[[0m ^[[0m^[[1m^[[0mnumvcpus^[[0m^[[0m               = "2"
      ^[[32m+^[[0m ^[[0m^[[1m^[[0movf_properties_timer^[[0m^[[0m   = (known after apply)
      ^[[32m+^[[0m ^[[0m^[[1m^[[0mpower^[[0m^[[0m                  = "off"
      ^[[32m+^[[0m ^[[0m^[[1m^[[0mresource_pool_name^[[0m^[[0m     = (known after apply)
      ^[[32m+^[[0m ^[[0m^[[1m^[[0mvirthwver^[[0m^[[0m              = (known after apply)

      ^[[32m+^[[0m ^[[0mnetwork_interfaces {
2020/04/09 11:58:18 [TRACE] Completed graph transform *terraform.CloseProviderTransformer with new graph:
`
`2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:    config = (vim.vm.Summary.ConfigSummary) {
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       name = "light.delestrez.local",
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       template = false,
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       vmPathName = "[Main] light.delestrez.local/light.delestrez.local.vmx",
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       memorySizeMB = 4096,
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       cpuReservation = 0,
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       memoryReservation = 0,
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       numCpu = 1,
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       numEthernetCards = 1,
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       numVirtualDisks = 1,
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       uuid = "564da079-4a8c-78ba-0047-75ffdacf7201",
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       instanceUuid = "527231bd-5d9a-d521-625b-4dff3cfc67c1",
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       guestId = "centos64Guest",
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       guestFullName = "CentOS 4/5/6/7 (64-bit)",
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       annotation = "",
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       product = (vim.vApp.ProductInfo) null,
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       installBootRequired = <unset>,
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       ftInfo = (vim.vm.FaultToleranceConfigInfo) null,
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:       managedBy = (vim.ext.ManagedByInfo) null
2020-04-09T12:01:20.701Z [DEBUG] plugin.terraform-provider-esxi_v1.6.4:    }`


> If you run terraform plan/apply again a second time, does it "fix" or attempt to fix the number of vcpus?

Nope, I fix it manually usually. When I tried right now, I got:
`Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

esxi_guest.light: Modifying... [id=42]

Error: Failed to grow boot disk.

  on freeipa.tf line 1, in resource "esxi_guest" "light":
   1: resource "esxi_guest" "light" {
`

**Comment by josenk** [comment]
That looks like a pretty basic tf file...    I'll need more information.   Have you tried cloning other vms?

Can you attach the contents of the vmx files from "template-centos-7" and "light".

**Comment by DimDroll** [comment]
> That looks like a pretty basic tf file... I'll need more information. Have you tried cloning other vms?
I just did and got the same error:
```
Error: [guestCREATE] Failed to grow boot disk.
```
This is when I try with other powered off VM (which was created based on template-centos-7 though).

> Can you attach the contents of the vmx files from "template-centos-7" and "light".
**template-centos-7**
```
.encoding = "UTF-8"
config.version = "8"
virtualHW.version = "11"
vmci0.present = "TRUE"
floppy0.present = "FALSE"
memSize = "1024"
bios.bootRetry.delay = "10"
sched.cpu.units = "mhz"
sched.cpu.affinity = "all"
powerType.suspend = "soft"
tools.upgrade.policy = "manual"
scsi0.virtualDev = "lsilogic"
scsi0.present = "TRUE"
sata0.present = "TRUE"
scsi0:0.deviceType = "scsi-hardDisk"
scsi0:0.fileName = "template-centos-70-000006.vmdk"
sched.scsi0:0.shares = "normal"
scsi0:0.present = "TRUE"
ethernet0.virtualDev = "vmxnet3"
ethernet0.networkName = "VM Network"
ethernet0.addressType = "generated"
ethernet0.wakeOnPcktRcv = "FALSE"
ethernet0.present = "TRUE"
displayName = "template-centos-7"
guestOS = "centos-64"
toolScripts.afterPowerOn = "TRUE"
toolScripts.afterResume = "TRUE"
toolScripts.beforeSuspend = "TRUE"
toolScripts.beforePowerOff = "TRUE"
tools.syncTime = "FALSE"
uuid.bios = "56 4d 20 e5 c2 df 87 29-04 1b 46 fb a2 a8 62 b9"
uuid.location = "56 4d 20 e5 c2 df 87 29-04 1b 46 fb a2 a8 62 b9"
vc.uuid = "52 2a 9d 0a 75 97 6e 0c-59 de 55 ec f7 2b eb d5"
sched.cpu.min = "0"
sched.cpu.shares = "normal"
sched.mem.min = "0"
sched.mem.minSize = "0"
sched.mem.shares = "normal"
vmci0.id = "-1566022983"
extendedConfigFile = "template-centos-7.vmxf"
cleanShutdown = "TRUE"
tools.guest.desktop.autolock = "false"
nvram = "template-centos-7.nvram"
pciBridge0.present = "TRUE"
svga.present = "TRUE"
pciBridge4.present = "TRUE"
pciBridge4.virtualDev = "pcieRootPort"
pciBridge4.functions = "8"
pciBridge5.present = "TRUE"
pciBridge5.virtualDev = "pcieRootPort"
pciBridge5.functions = "8"
pciBridge6.present = "TRUE"
pciBridge6.virtualDev = "pcieRootPort"
pciBridge6.functions = "8"
pciBridge7.present = "TRUE"
pciBridge7.virtualDev = "pcieRootPort"
pciBridge7.functions = "8"
hpet0.present = "true"
RemoteDisplay.maxConnections = "-1"
sched.cpu.latencySensitivity = "normal"
sched.scsi0:0.throughputCap = "off"
ethernet0.uptCompatibility = "TRUE"
vcpu.hotadd = "true"
virtualHW.productCompatibility = "hosted"
sched.swap.derivedName = "/vmfs/volumes/5d2de487-fe381980-9414-002590c2c41c/template-centos-7/template-centos-7-62a17829.vswp"
replay.supported = "false"
pciBridge0.pciSlotNumber = "17"
pciBridge4.pciSlotNumber = "21"
pciBridge5.pciSlotNumber = "22"
pciBridge6.pciSlotNumber = "23"
pciBridge7.pciSlotNumber = "24"
scsi0.pciSlotNumber = "16"
ethernet0.pciSlotNumber = "160"
vmci0.pciSlotNumber = "32"
sata0.pciSlotNumber = "33"
ethernet0.generatedAddressOffset = "0"
monitor.phys_bits_used = "42"
vmotion.checkpointFBSize = "4194304"
vmotion.checkpointSVGAPrimarySize = "4194304"
softPowerOff = "TRUE"
svga.guestBackedPrimaryAware = "TRUE"
tools.remindInstall = "FALSE"
checkpoint.vmState.readOnly = "FALSE"
migrate.hostLog = "./template-centos-7-62a17829.hlog"
```

**light**
```
.encoding = "UTF-8"
config.version = "8"
displayName = "light.delestrez.local"
floppy0.present = "FALSE"
guestOS = "centos-64"
memSize = "4096"
powerType.suspend = "soft"
sata0.present = "TRUE"
scsi0.present = "TRUE"
scsi0.virtualDev = "lsilogic"
scsi0:0.deviceType = "scsi-hardDisk"
scsi0:0.fileName = "light.delestrez.local.vmdk"
scsi0:0.present = "TRUE"
toolScripts.afterPowerOn = "TRUE"
toolScripts.afterResume = "TRUE"
toolScripts.beforePowerOff = "TRUE"
toolScripts.beforeSuspend = "TRUE"
tools.syncTime = "FALSE"
tools.upgrade.policy = "manual"
uuid.bios = "56 4d a0 79 4a 8c 78 ba-00 47 75 ff da cf 72 01"
uuid.location = "56 4d a0 79 4a 8c 78 ba-00 47 75 ff da cf 72 01"
vc.uuid = "52 72 31 bd 5d 9a d5 21-62 5b 4d ff 3c fc 67 c1"
virtualHW.version = "11"
vmci0.present = "TRUE"

ethernet0.networkName = "VM Network"
ethernet0.virtualDev = "e1000"
ethernet0.present = "TRUE"

sched.scsi0:0.throughputCap = "off"
numvcpus = "2"
sched.cpu.units = "mhz"
sched.cpu.affinity = "all"
sched.cpu.latencySensitivity = "normal"
sched.scsi0:0.shares = "normal"
ethernet0.addressType = "generated"
ethernet0.wakeOnPcktRcv = "FALSE"
tools.guest.desktop.autolock = "FALSE"
guestinfo.userdata = "H4sIAAAAAAAA/4yRwUozMRSF932K888PdqFpoCtx0ZUL38CFEUmTOzPBzL0hSVspPrzMOIqCI+5uyPedE27+uygHr5xwG7rVKh/YDf5mBQAK3lbCTmeRqicucKibKN1830upbAdyNaJQVR9nxND1deMpUqmZzpsozsZZItcL7ihGwb3k6P9h90vF3pYeymE9aYrQeMNbw2w4TYPhS8N1Gq/J8KnBK1ofyjO0p6Mu3uLix4L13JBsrinLnkYOyy9Jx0wlnOkzd7sQPPPxGz/YlChrR1ylqFH6a84DXtry1GU5teUKGo9f99jcChPe/3D0moVlvgEAAP//AQAA//+QV6Q15wEAAA=="
guestinfo.userdata.encoding = "gzip+base64"
hpet0.present = "true"
nvram = "light.delestrez.local.nvram"
pciBridge0.present = "TRUE"
pciBridge4.functions = "8"
pciBridge4.present = "TRUE"
pciBridge4.virtualDev = "pcieRootPort"
pciBridge5.functions = "8"
pciBridge5.present = "TRUE"
pciBridge5.virtualDev = "pcieRootPort"
pciBridge6.functions = "8"
pciBridge6.present = "TRUE"
pciBridge6.virtualDev = "pcieRootPort"
pciBridge7.functions = "8"
pciBridge7.present = "TRUE"
pciBridge7.virtualDev = "pcieRootPort"
sata0.pciSlotNumber = "33"
scsi0.pciSlotNumber = "16"
svga.present = "TRUE"
vcpu.hotadd = "true"
vmci0.pciSlotNumber = "32"
disk.EnableUUID = "true"
sched.cpu.min = "0"
sched.cpu.shares = "normal"
sched.mem.min = "0"
sched.mem.minSize = "0"
sched.mem.shares = "normal"
virtualHW.productCompatibility = "hosted"
sched.swap.derivedName = "/vmfs/volumes/5d2de487-fe381980-9414-002590c2c41c/light.delestrez.local/light.delestrez.local-9ae51f81.vswp"
replay.supported = "FALSE"
replay.filename = ""
migrate.hostlog = "./light.delestrez.local-9ae51f81.hlog"
scsi0:0.redo = ""
pciBridge0.pciSlotNumber = "17"
pciBridge4.pciSlotNumber = "21"
pciBridge5.pciSlotNumber = "22"
pciBridge6.pciSlotNumber = "23"
pciBridge7.pciSlotNumber = "24"
ethernet0.pciSlotNumber = "34"
ethernet0.generatedAddress = "00:0c:29:cf:72:01"
ethernet0.generatedAddressOffset = "0"
vmci0.id = "-623939071"
monitor.phys_bits_used = "42"
vmotion.checkpointFBSize = "4194304"
vmotion.checkpointSVGAPrimarySize = "4194304"
cleanShutdown = "TRUE"
softPowerOff = "TRUE"
svga.guestBackedPrimaryAware = "TRUE"
```
Sorry for the long-read, I'm not sure where I can upload here.

**Comment by josenk** [comment]
Light has numvcpus = "2"...  Not sure where your problem is???

**Comment by DimDroll** [comment]
> Light has numvcpus = "2"... Not sure where your problem is???

@josenk You're right, apologize. That's after I manually change it to 2 cpus through UI.
Here is another vmx from test.local VM cloned in a described way:
```
.encoding = "UTF-8"
config.version = "8"
virtualHW.version = "11"
nvram = "test.local.nvram"
pciBridge0.present = "TRUE"
svga.present = "TRUE"
pciBridge4.present = "TRUE"
pciBridge4.virtualDev = "pcieRootPort"
pciBridge4.functions = "8"
pciBridge5.present = "TRUE"
pciBridge5.virtualDev = "pcieRootPort"
pciBridge5.functions = "8"
pciBridge6.present = "TRUE"
pciBridge6.virtualDev = "pcieRootPort"
pciBridge6.functions = "8"
pciBridge7.present = "TRUE"
pciBridge7.virtualDev = "pcieRootPort"
pciBridge7.functions = "8"
vmci0.present = "TRUE"
hpet0.present = "TRUE"
floppy0.present = "FALSE"
memSize = "1024"
powerType.suspend = "soft"
tools.upgrade.policy = "manual"
scsi0.virtualDev = "lsilogic"
scsi0.pciSlotNumber = "16"
scsi0.present = "TRUE"
sata0.pciSlotNumber = "33"
sata0.present = "TRUE"
scsi0:0.deviceType = "scsi-hardDisk"
scsi0:0.fileName = "test.local.vmdk"
scsi0:0.present = "TRUE"
vmci0.pciSlotNumber = "32"
displayName = "test.local"
guestOS = "centos-64"
vcpu.hotadd = "TRUE"
toolScripts.afterPowerOn = "TRUE"
toolScripts.afterResume = "TRUE"
toolScripts.beforeSuspend = "TRUE"
toolScripts.beforePowerOff = "TRUE"
tools.syncTime = "FALSE"
uuid.bios = "56 4d d1 71 6c 17 3c 8b-24 59 3f 49 b9 43 e7 59"
uuid.location = "56 4d d1 71 6c 17 3c 8b-24 59 3f 49 b9 43 e7 59"
vc.uuid = "52 03 e0 2b 0b 8a b4 b9-bb 49 9f e2 0d 5f ca f4"
ethernet0.networkName = "VM Network"
ethernet0.virtualDev = "e1000"
ethernet0.present = "TRUE"

disk.EnableUUID = "TRUE"
```

**Comment by jlundy2** [comment]
I am getting the same issue with the following warning:

```
2020/04/20 14:54:39 [WARN] Provider "registry.terraform.io/-/esxi" produced an unexpected new value for esxi_guest.vmtest02, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .numvcpus: was cty.StringVal("2"), but now cty.StringVal("")
```

I am getting no other errors

**Comment by josenk** [comment]
Does your source vmx have a numvcpu variable set?

**Comment by josenk** [comment]
BTW:
  * This "complaint" by terraform  `numvcpus: was cty.StringVal("2"), but now cty.StringVal("")` simply means, the plugin is declaring it's setting numvcpus to 2, but after the apply, the plugin is returning "".
  * It's returning nothing ("") because there is no "numvcpu" variable in the vmx file...  So that message is not really a problem.   It's just saying the plugin is not doing what it should. 

So far, I'm not able to reproduce your problem...   Try rebooting your esxi host.

**Comment by josenk** [comment]
When you have enough details to provide an exact way to re-create this problem, please open a new ticket.
