### ISSUE TITLE
Cloudbase-Init support

### ISSUE THREAD

**Issue by taislapta** [josenk/terraform-provider-esxi#138]
Hey, 
thanks for tf  esxi provider, that helps a lot. 
Just wondering if there are  any plans to add  Cloudbase-Init support in to the  roadmap ?

[Cloudbase-Init](https://cloudbase.it/cloudbase-init/) is the Windows equivalent of the Cloud-Init project used on most OpenStack Linux images. When deployed as a service on Windows, Cloudbase-Init takes care of all the guest initialization actions: disk volume expansion, user creation, password generation, custom PowerShell, CMD and Bash scripts execution, Heat templates, PowerShell remoting setup and much more.

**Comment by josenk** [comment]
Sorry, but supporting the Windows equivalent of cloud-init doesn't depend on terraform-provider-esxi (or ANY provider for that matter)...   You need to request that feature from the developers of that utility.  The list of hypervisors and services on their web site doesn't include VMware or ESXi, so I'll assume that's why it doesn't work...   
>https://cloudbase.it/cloudbase-init/

cloud-init needs to pull the userdata from the VMware Guestinfo interface.   You can read about it here and maybe ask the developer to include Windows support???
>https://github.com/vmware/cloud-init-vmware-guestinfo


Remember:  This provider creates your VMs, it doesn't configure it. 
>https://github.com/josenk/terraform-provider-esxi#this-is-a-provider--not-a-provisioner

**Comment by taislapta** [comment]
thanks, that make sense
