### ISSUE TITLE
Clone all disk not cloned

### ISSUE THREAD

**Issue by Demonium** [josenk/terraform-provider-esxi#179]
**Describe the bug**
When cloning a system  with multiple hard disk only the first one is cloned.

**To Reproduce**
1. terraform plan/apply/
2. no error

**Expected behavior**
A full copy of the original system (all disks)

**Terraform files**
resource "esxi_guest" "vmtest02" {
  guest_name = "vmtest02"
  disk_store = "datastore1"
  guestos    = "centos-64"

  memsize            = "2048"
  numvcpus           = "2"
  resource_pool_name = "/"
  power              = "on"

  clone_from_vm = "centos7"

  network_interfaces {
    virtual_network = "VM Network"
  }
  guest_startup_timeout  = 45
  guest_shutdown_timeout = 30
}

**Desktop (please complete the following information):**
 - OS: [e.g. Linux/Mac/Windows Ver 1.2.3] SLES15SP3
 - Terraform Version: [e.g. 0.12.9] 0.13
 - Ovftool Version:4.4.3

**Additional context**
none

**Comment by Demonium** [comment]
Hello,
Additionnal information: during the cloning phase the disk contains the good size in the parameters, once the clone is finish the disk hasn't got the good size and the second disk is not displayed

**Comment by josenk** [comment]
This is expected behavior.
  This terraform provider manages the vm and is also able to manage all the additional disks.   If a disk was unexpectedly copied during a clone, terraform considers this as something created outside it's management and would 'make it right' by deleting it, or overwritting it.  It would be a nightmare to trying to support a use-case like this.

**Comment by josenk** [comment]
correct.
